we can create arrays in numpy by either casting a list or by arange

    creating a list

In [1]:
my_list = [1,2,3]

In [2]:
my_list


[1, 2, 3]

In [ ]:
#casting a list into array

In [3]:
import numpy as np

In [7]:
np.array(my_list)

array([1, 2, 3])

assigning

In [8]:
arr=np.array(my_list)

In [9]:
arr

array([1, 2, 3])

     casting list of lists in array

In [12]:
list_list=[[1,2,3],[2,3,4],[5,6,7]]

In [13]:
np.array(list_list)

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [ ]:
#arange:easier way to create arrays
         (start,stop)

In [17]:
np.arange(0,7) 

array([0, 1, 2, 3, 4, 5, 6])

      another way(start,stop,step)

In [18]:
np.arange(0,7,2)

array([0, 2, 4, 6])

     if you want array of zeros or ones

In [19]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

    [[ ]]means 2d   [[[]]]3d

In [ ]:
#linspace
#returns evenly spaced numbers over a specified interval

In [2]:
import numpy as np

In [6]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [8]:
np.linspace(2,10,2)

array([ 2., 10.])

In [15]:
np.linspace(1,10,9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
#Identity matrix:a square matrix with 1 as its diagonal

In [3]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#random:creates array of random numbers

    random.rand:method (btw 0 and 1:0 and 1 excluded)
    rand uniformly distributes numbers (eqaul likely to occur)

In [4]:
np.random.rand(4)

array([0.83833246, 0.70539473, 0.33960739, 0.43094317])

In [5]:
np.random.rand(3)

array([0.13718803, 0.97829084, 0.53195216])

In [6]:
np.random.rand(4,4)

array([[0.60297679, 0.91395669, 0.3205926 , 0.58643519],
       [0.37389031, 0.58774785, 0.57389324, 0.6670651 ],
       [0.55427328, 0.05372933, 0.18126653, 0.66379161],
       [0.00853413, 0.48610526, 0.12961618, 0.50371265]])

    np.random.randn():returns most of the values clustered closer to 0

In [7]:
np.random.randn(4)

array([ 0.05100261, -0.31983784,  0.73207526, -1.04012923])

In [8]:
np.random.randn(4,3)

array([[-4.00420786e-02, -2.34345266e-01, -2.44524336e-02],
       [-2.74887994e-01, -3.72387470e-01, -9.06521302e-01],
       [ 1.17926513e-03,  5.09221052e-01, -1.18844548e+00],
       [-2.00023802e+00, -5.65659063e-01, -2.67796281e-02]])

    np.random.randint(low:inclusive,high:exclusive,size)
    randint:random integers

In [9]:
np.random.randint(1,5,4)

array([1, 4, 1, 3])

In [13]:
arr=np.arange(25)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

    reshape is just changing array format without changing its size

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr=np.random.randint(2,20,14)

In [26]:
ranarr

array([ 2,  3, 14, 19, 17,  6, 10, 11, 18, 15,  5,  3, 14, 19])

    returns max and min value

In [22]:
ranarr.max()

19

In [23]:
ranarr.min()

2

    arg returns location or index values

In [24]:
ranarr.argmax()

3

In [28]:
ranarr.argmin()

0

    shape is to know an arrays actual shape(in 1d or 2d)

In [29]:
ranarr.shape

(14,)

In [32]:
arr.shape

(25,)

In [33]:
arr=arr.reshape(5,5)

In [34]:
arr.shape

(5, 5)

In [ ]:
#dtpe is datatype in array
here integers are of 32 bitsize

In [35]:
arr.dtype

dtype('int32')

In [ ]:
#TIP(applied to all)eg:
instead of typing np.random.randint...
type;from numpy.random import randint

In [37]:
from numpy.random import randint

In [38]:
randint(1,5)

1

In [ ]:
#NUMPY INDEXING (same as python list)

In [ ]:
#indexing an array

In [4]:
import numpy as np

    arange(0=index,11=size)

In [32]:
arr=np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

    we do indexing by brackets[] for a value

In [34]:
arr[6]

6

    or slice notations[2:5] for returning range of values

In [39]:
arr[4:5]

array([4])

In [15]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

    broadcast:difference of numpy indexing from python list
    broadcasting means copying an input to wherever required

In [37]:
arr[6]=100

In [38]:
arr

array([  0,   1,   2,   3,   4,   5, 100,   7,   8,   9,  10])

    if array is reset,we get old array

In [40]:
arr=np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
slice_of_arr=arr[0:4]

In [45]:
slice_of_arr

array([0, 1, 2, 3])

    broadcasting the slice to another number

In [46]:
slice_of_arr[0:4]=55

In [47]:
slice_of_arr

array([55, 55, 55, 55])

    but broadcasting changed the original array
    (np doesnt store copies of arrays to avoid memory issues)

In [48]:
arr

array([55, 55, 55, 55,  4,  5,  6,  7,  8,  9, 10])

    to retain the original array values..we make copy[arr.copy()]

In [49]:
arr_copy=arr.copy()

In [50]:
arr_copy

array([55, 55, 55, 55,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr_copy[4:6]=44

In [52]:
arr_copy

array([55, 55, 55, 55, 44, 44,  6,  7,  8,  9, 10])

In [53]:
arr

array([55, 55, 55, 55,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#indexing a 2d array(matrix)
indexing start with 0

In [117]:
arr_2d=np.array([[67,45,34],[23,22,21],[89,87,85]])

In [118]:
arr_2d

array([[67, 45, 34],
       [23, 22, 21],
       [89, 87, 85]])

    2 general format for grabbing element from 2d array:[row][col]/[row,col]
    

In [119]:
arr_2d[1][1]

22

In [120]:
arr_2d[1,1]

22

In [121]:
arr_2d[1]

array([23, 22, 21])

    2d array slicing:to grab sections of array(notsoimp)

In [122]:
arr_2d[1:]

array([[23, 22, 21],
       [89, 87, 85]])

In [131]:
arr_2d[1:,1:]

array([[22, 21],
       [87, 85]])

In [136]:
arr_2d[:2,:2]

array([[67, 45],
       [23, 22]])

In [ ]:
#conditional selection(imp)
it returns boolean array when comparision op is given to array
we can take the true values

In [137]:
arr=np.arange(0,10)

In [138]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
bool_arr=arr>4

In [140]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [141]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

    to write it simply

In [142]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [ ]:
#practice

In [143]:
arr=np.arange(50).reshape(5,10)

In [144]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr[1:3,1:3]

array([[11, 12],
       [21, 22]])